# Generated by Django 4.2.7 on 2025-01-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopUp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank',
            field=models.CharField(blank=True, choices=[('BRI', 'BRI'), ('BCA', 'BCA'), ('BTN', 'BTN')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ewallet',
            field=models.CharField(blank=True, choices=[('DANA', 'DANA'), ('OVO', 'OVO'), ('GoPay', 'GoPay')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='game_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('E-wallet', 'E-wallet'), ('Bank Transfer', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='zone_id',
            field=models.CharField(max_length=100),
        ),
    ]
